name: Enhancement Request
description: Suggest an improvement or new feature for the application.
title: "[ENHANCEMENT]"
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        ## Enhancement Request
        Please provide detailed information about the improvement or feature suggestion.

  - type: textarea
    id: enhancement-description
    attributes:
      label: Description of the enhancement
      description: A clear and concise description of the feature or improvement.
      placeholder: Describe the enhancement you would like to see.
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: false

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any other options you've thought about.
    validations:
      required: false
