name: Close inactive issues
on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 */3 * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          exempt-issue-labels: "no-stale"
          days-before-issue-stale: 30
          days-before-issue-close: 60
          stale-issue-label: "stale"
          stale-issue-message: "This issue has been marked as stale due to inactivity."
          close-issue-message: "This issue was closed after being stale with no activity."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
