name: Publish o99 WinGet Manifest
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-winget:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download latest.json
        run: Invoke-WebRequest "https://github.com/o9-9/o99/releases/download/v1.4.1/latest.json" -OutFile latest.json

      - name: Parse latest.json and update manifest
        shell: pwsh
        run: |
          $json = Get-Content latest.json | ConvertFrom-Json
          $version = $json.version
          $url = $json.platforms.'windows-x86_64'.url

          # Read manifest template
          $manifestPath = ".winget/o9-9.o99.yaml"
          $manifest = Get-Content $manifestPath

          # Update Version and Url in manifest
          $manifest = $manifest -replace "Version:.*", "Version: $version"
          $manifest = $manifest -replace "Url:.*", "Url: $url"

          # Save updated manifest
          Set-Content -Path $manifestPath -Value $manifest

      - name: Download wingetcreate
        run: Invoke-WebRequest https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe

      - name: Submit manifest to WinGet repo
        run: .\wingetcreate.exe submit --token "${{ secrets.WINGET_TOKEN }}" .winget/o9-9.o99.yaml
